#$ -S /bin/bash

#$ -V

#$ -cwd

#$ -j y

#$ -N dilltest

#$ -R y

#$ -o /home/dbrout/pysmp_standalone/output/


#$ -pe ompi 1

#$ -l h_rt=00:55:00

source activate condasmp

date

myvar=$(expr $SGE_TASK_ID + 1)

python mcmc_manager.py --index=$(expr $SGE_TASK_ID \* 8 - 8) >> /home/dbrout/pysmp_standalone/output/log.log &
python mcmc_manager.py --index=$(expr $SGE_TASK_ID \* 8 - 7) >> /home/dbrout/pysmp_standalone/output/log.log &
python mcmc_manager.py --index=$(expr $SGE_TASK_ID \* 8 - 6) >> /home/dbrout/pysmp_standalone/output/log.log &
python mcmc_manager.py --index=$(expr $SGE_TASK_ID \* 8 - 5) >> /home/dbrout/pysmp_standalone/output/log.log &
python mcmc_manager.py --index=$(expr $SGE_TASK_ID \* 8 - 4) >> /home/dbrout/pysmp_standalone/output/log.log &
python mcmc_manager.py --index=$(expr $SGE_TASK_ID \* 8 - 3) >> /home/dbrout/pysmp_standalone/output/log.log &
python mcmc_manager.py --index=$(expr $SGE_TASK_ID \* 8 - 2) >> /home/dbrout/pysmp_standalone/output/log.log &
python mcmc_manager.py --index=$(expr $SGE_TASK_ID \* 8 - 1) >> /home/dbrout/pysmp_standalone/output/log.log &

wait

date
