#$ -S /bin/bash

#$ -V

#$ -cwd

#$ -j y

#$ -N zband_dilltest

#$ -R y

#$ -l des

#$ -o /home/dbrout/pysmp_standalone/output/

#$ -pe ompi 1

#$ -tc 200

source activate condasmp2

cd /home/dbrout/pysmp_standalone

date

myvar="/home/dbrout/pysmp_standalone/npzfiles"

outpath="/home/dbrout/pysmp_standalone/fitout"

python mcmc_manager.py --index=$SGE_TASK_ID --npzfolder=$myvar --outpath=$outpath >> /home/dbrout/pysmp_standalone/output/log.log

date



